[package]
name = "ray"
version = "0.1.0"
authors = ["tttmmmyyyy <39012639+tttmmmyyyy@users.noreply.github.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.15.3"
image = "0.19.0"
rand = "0.5.5"
crossbeam = "0.5.0" 
itertools = "0.8.0"